### ISSUE TITLE
Help importing into Custom system builder

### ISSUE THREAD

**Issue by jodamajster** [SvenWerlen/fvtt-data-toolbox#32]
[cennik warhammer.csv](https://github.com/SvenWerlen/fvtt-data-toolbox/files/10276653/cennik.warhammer.csv)
[item-template.json.txt](https://github.com/SvenWerlen/fvtt-data-toolbox/files/10276666/item-template.json.txt)
[how it looks in item db.json.txt](https://github.com/SvenWerlen/fvtt-data-toolbox/files/10276675/how.it.looks.in.item.db.json.txt)
hello Please aid me im trying to import stuff into CSB

> Uncaught (in promise) Error: SyntaxError: Expected double-quoted property name in JSON at position 213
[Detected 1 package: data-toolbox]
    at GenerateCompendiumDialog._generate (data-toolbox.js:186:15)

> 

I don't know where I Failed or if it's my fault. I'm attaching files I was working with

Also! Can I create folders with this? the "type" column actually was planed to be folder names. i I can generate folders alongside items

**Comment by SvenWerlen** [comment]
Sorry for my late answer. Pretty busy atm.
Your template doesn't generate valid JSON file. 
You had comma (`,`) at the end of a dict, which is not valid.
I recommend to use a JSON validator like https://jsonformatter.org/ to validate the output (which is rendered in the console).

Fixed : 
[item-template.json.txt](https://github.com/SvenWerlen/fvtt-data-toolbox/files/11035202/item-template.json.txt)

Note : the above template is valid but won't work with DnD5 because it's missing some required fields.
