### ISSUE TITLE
Undefined error in Json

### ISSUE THREAD

**Issue by FuzzySadist** [SvenWerlen/fvtt-data-toolbox#33]
I've created my CSV and JSON files... I can't find anything wrong with either... but I keep getting this error

foundry.js:59187 Generation failed. Check console for more details!
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
_generate @ data-toolbox.js:184
data-toolbox.js:185 Data Toolbox | JSON: {
  "name": "undefined",
  "type": "consumable",
  "img": "undefined",
  "system": {
    "description": "",
    "favorite": false,
    "weight": 1,
    "cost": "20",
    "quantity": 1,
    "rarity": 2,
    "stashed": false,
    "consumableType": "beverage",
    "hp": undefined,
    "effect": "<div>undefined</div>",
    "irradiated": undefined,
    "alcoholic": false,
    "duration": "",
    "addictive": ""
  },
  "effects": [],
  "flags": {
    "exportSource": {
      "world": "for-a-few-caps-more",
      "system": "fallout",
      "coreVersion": "10.291",
      "systemVersion": "10.1.1"
    }
  },
  "_stats": {
    "systemId": "fallout",
    "systemVersion": "10.0.0",
    "coreVersion": "10.291",
    "createdTime": 1676538045517,
    "modifiedTime": 1676538178565,
    "lastModifiedBy": "UuAOc3SIuULCM6oI"
  }
}
data-toolbox.js:186 Uncaught (in promise) Error: undefined. SyntaxError: Unexpected token 'u', ..."    "hp": undefined,"... is not valid JSON
[Detected 1 package: data-toolbox]
    at GenerateCompendiumDialog._generate (data-toolbox.js:186:15)

Help?

[templates.zip](https://github.com/SvenWerlen/fvtt-data-toolbox/files/10956477/templates.zip)

**Comment by SvenWerlen** [comment]
The module outputs the generated JSON when it is not valid. 
You can use a JSON validator like https://jsonformatter.org/ to understand why it's not valid.
I highlighted in the screenshot below all the errors
![image](https://user-images.githubusercontent.com/938060/226773851-ccac70bf-878b-409a-a754-33b75fbb85eb.png)

One of the reasons why this happens is because you use `{{name}}` as header in your template rather than `name`. So, the module is not able to match the fields and everything comes out as `undefined`.

**Comment by SvenWerlen** [comment]
Feel free to re-open it if you need further assistance.
